### PR TITLE
Refactors twitter protocol exception handling

### PR DESCRIPTION
**Pull request by iferminm**
This proposes a different approach on handling exceptions related to code errors from a third party API, doesn't really improve anything or optimize the performance but in my opinion this is more readable than the conditional sequence we had before and defines a better separation of concerns delegating the correct exception class resolution to the exceptions module.

### CODE REVIEW

**Comment by satanas** [comment]
It looks great, I like the way you handle the exceptions here. However I'm trying to run the tests and there are 8 errors related to these changes. Could you fix them to merge the PR?

Execute pytest on the root of the project to run the tests:

`py.test --cov libturpial --cov-config .coveragerc tests/`

**Comment by iferminm** [comment]
Sure!, I'll do it today :-). Thank you :-)

**Comment by iferminm** [comment]
done, but there are a lot of issues related to AppConfig that I can't debug at the moment.

**Comment by iferminm** [comment]
@satanas done, test cases fixed, sorry for taking this long, had a couple of hectic weeks at work, it was a really silly bug. So... I fixed it by assuming secure proxy if not specified because the protocol don't always comes on the config, but when it does, it's http xD. Cheers!

**Pull request merged**
